dialogue_lines = [
    {"character": "Claudius", "text": "I have sent to seek him and to find the body.", "type": "iambic", "choices": None},
    {"character": "Claudius", "text": "How dangerous is it that this man goes loose!", "type": "iambic", "choices": None},

    {"character": "Question", "text": ("What does it connect to?"), "type": "prose", "choices": [
        {"text": "Madness", "correct": True},
        {"text": "Fate & Great Chain of Being", "correct": False} ]},
    
    {"character": "Claudius", "text": "Yet must not we put the strong law on him.", "type": "iambic", "choices": None},
    {"character": "Claudius", "text": "He's loved of the distracted multitude,", "type": "iambic", "choices": None},
    {"character": "Claudius", "text": "Who like not in their judgment, but their eyes;", "type": "iambic", "choices": None},
    {"character": "Claudius", "text": "And, where 'tis so, th' offender's scourge is weighed,", "type": "iambic", "choices": None},
    {"character": "Claudius", "text": "But never the offense. To bear all smooth and even,", "type": "iambic", "choices": None},

    {"character": "Question", "text": ("What theme does the above passage connect to?"), "type": "prose", "choices": [
        {"text": "State vs Family Priorities", "correct": False},
        {"text": "Appearance vs Reality", "correct": True} ]},
    
    {"character": "Claudius", "text": "This sudden sending him away must seem", "type": "iambic", "choices": None},
    {"character": "Claudius", "text": "Deliberate pause. Diseases desperate grown", "type": "iambic", "choices": None},

    {"character": "Question", "text": ("What does the above quote potentially connect to?"), "type": "prose", "choices": [
        {"text": "Hamlet Speaking with Daggers", "correct": False},
        {"text": "Gertrude's Black and Grained Spots", "correct": True} ]},

    {"character": "Claudius", "text": "By desperate appliance are relieved", "type": "iambic", "choices": None},
    {"character": "Claudius", "text": "Or not at all.", "type": "iambic", "choices": None},
    
    {"character": "Rosencrantz", "text": "Where the dead body is bestowed, my lord,", "type": "iambic", "choices": None},
    {"character": "Rosencrantz", "text": "We cannot get from him.", "type": "iambic", "choices": None},

    {"character": "Claudius", "text": "But where is he?", "type": "iambic", "choices": None},
    
    {"character": "Rosencrantz", "text": "Without, my lord; guarded, to know your pleasure.", "type": "prose", "choices": None},
    
    {"character": "Claudius", "text": "Bring him before us.", "type": "iambic", "choices": None},
    
    {"character": "Hamlet", "text": "At supper.", "type": "iambic", "choices": None},
    
    {"character": "Claudius", "text": "At supper where?", "type": "iambic", "choices": None},
    
    {"character": "Hamlet", "text": "Not where he eats, but where he is eaten.", "type": "prose", "choices": None},
    {"character": "Hamlet", "text": "A certain convocation of politic worms are e’en at him.", "type": "prose", "choices": None},
    {"character": "Hamlet", "text": "Your worm is your only emperor for diet.", "type": "prose", "choices": None},
    {"character": "Hamlet", "text": "We fat all creatures else to fat us, and we fat ourselves for maggots.", "type": "prose", "choices": None},
    {"character": "Hamlet", "text": "Your fat king and your lean beggar is but variable service—", "type": "prose", "choices": None},
    {"character": "Hamlet", "text": "two dishes but to one table. That’s the end.", "type": "prose", "choices": None},    
    
    {"character": "Question", "text": ("What does the Worm Symbolize the Best?"), "type": "prose", "choices": [
        {"text": "Polonius' Sins and the Entities above Eating Him", "correct": True},
        {"text": "Claudius' Morals as Dirty as Earthworms", "correct": False} ]},

    {"character": "Claudius", "text": "Alas, alas!", "type": "iambic", "choices": None},
    
    {"character": "Hamlet", "text": "A man may fish with the worm that hath eat of a king ", "type": "prose", "choices": None},
    {"character": "Hamlet", "text": "and eat of the fish that hath fed of that worm.", "type": "prose", "choices": None},

    {"character": "Question", "text": ("What does the worm, fish, and emperor connect to?"), "type": "prose", "choices": [
        {"text": "Inaction & Rebellion", "correct": False},
        {"text": "Fate & Great Chain of Being", "correct": True} ]},

    {"character": "Claudius", "text": "What dost thou mean by this?", "type": "iambic", "choices": None},
    
    {"character": "Hamlet", "text": "Nothing but to show you how a king may go a progress through the guts of a beggar.", "type": "prose", "choices": None},
    
    {"character": "Claudius", "text": "Where is Polonius?", "type": "iambic", "choices": None},
    
    {"character": "Hamlet", "text": "In heaven. Send thither to see.", "type": "prose", "choices": None},
    {"character": "Hamlet", "text": "If your messenger find him not there, seek him i’ th’ other place yourself.", "type": "prose", "choices": None},

    {"character": "Question", "text": ("What does Hamlet mean by that line?"), "type": "prose", "choices": [
        {"text": "Polonius is in purgatory, but Claudius can't find him because he'll be in Heaven", "correct": False},
        {"text": "Polonius is in hell, and Claudius can find him there where they both belong", "correct": True} ]},
    
    {"character": "Hamlet", "text": "But if, indeed, you find him not within this month, ", "type": "prose", "choices": None},
    {"character": "Hamlet", "text": "you shall nose him as you go up the stairs into the lobby.", "type": "prose", "choices": None},

    {"character": "Claudius", "text": "Go, seek him there.", "type": "iambic", "choices": None},
    
    {"character": "Hamlet", "text": "He will stay till you come.", "type": "prose", "choices": None},
    
    {"character": "Claudius", "text": ("Hamlet, this deed, for thine especial safety"), "type": "prose", "choices": None},
    {"character": "Claudius", "text": ("(Which we do tender, as we dearly grieve"), "type": "prose", "choices": None},
    {"character": "Claudius", "text": ("For that which thou hast done) must send thee hence "), "type": "prose", "choices": None},
    {"character": "Claudius", "text": ("With fiery quickness. Therefore prepare thyself."), "type": "prose", "choices": None},
    {"character": "Claudius", "text": ("The bark is ready, and the wind at help, "), "type": "prose", "choices": None},
    {"character": "Claudius", "text": ("Th’ associates tend, and everything is bent For England."), "type": "prose", "choices": None},
    
    {"character": "Question", "text": "What does Hamlet say?", "type": "iambic", "choices": [
        {"text": "To England?", "correct": True},
        {"text": "Wherefore not Wittenberg?", "correct": False}
    ]},

    {"character": "Claudius", "text": "Ay, Hamlet.", "type": "iambic", "choices": None},
    
    {"character": "Hamlet", "text": "Good.", "type": "iambic", "choices": None},
    
    {"character": "Claudius", "text": "So is it, if thou knew’st our purposes.", "type": "iambic", "choices": None},
    
    {"character": "Hamlet", "text": "I see a cherub that sees them. But come, for England. Farewell, dear mother.", "type": "prose", "choices": None},
    
    {"character": "Claudius", "text": "Thy loving father, Hamlet.", "type": "iambic", "choices": None},
    
    {"character": "Hamlet", "text": ("My mother. Father and mother is man and wife,"), "type": "prose", "choices": None},
    {"character": "Hamlet", "text": "Man and wife is one flesh, and so, my mother.—Come, for England.", "type": "iambic", "choices": None},

    {"character": "Hamlet", "text": "He exits.", "type": "iambic", "choices": None},
    {"character": "Claudius", "text": ("Follow him at foot; tempt him with speed aboard."), "type": "prose", "choices": None},
    {"character": "Claudius", "text": ("Delay it not. I’ll have him hence tonight."), "type": "prose", "choices": None},
    {"character": "Claudius", "text": ("Away, for everything is sealed and done"), "type": "prose", "choices": None},
    {"character": "Claudius", "text": ("That else leans on th’ affair."), "type": "prose", "choices": None},

    {"character": "Claudius", "text": "Pray you, make haste. All but the King exit.", "type": "prose", "choices": None},
    {"character": "Claudius", "text": ("And England, if my love thou hold’st at aught"), "type": "prose", "choices": None},
    {"character": "Claudius", "text": ("(As my great power thereof may give thee sense, "), "type": "prose", "choices": None},
    {"character": "Claudius", "text": ("Since yet thy cicatrice looks raw and red"), "type": "prose", "choices": None},
    {"character": "Claudius", "text": ("After the Danish sword, and thy free awe "), "type": "prose", "choices": None},

    {"character": "Question", "text": ("What theme does the above passage connect to?"), "type": "prose", "choices": [
        {"text": "Grief and Resentment", "correct": False},
        {"text": "Appearance vs Reality", "correct": True} ]},
    
    {"character": "Claudius", "text": ("Pays homage to us), thou mayst not coldly set "), "type": "prose", "choices": None},
    {"character": "Claudius", "text": ("Our sovereign process, which imports at full,"), "type": "prose", "choices": None},
    {"character": "Claudius", "text": ("By letters congruing to that effect,"), "type": "prose", "choices": None},
    {"character": "Claudius", "text": ("The present death of Hamlet. Do it, England,"), "type": "prose", "choices": None},

    {"character": "Claudius", "text": ("For like the hectic in my blood he rages,"), "type": "prose", "choices": None},
    {"character": "Claudius", "text": ("And thou must cure me. Till I know ’tis done,"), "type": "prose", "choices": None},
    {"character": "Claudius", "text": ("Howe’er my haps, my joys will ne’er begin."), "type": "prose", "choices": None},
    {"character": "Claudius", "text": ("The present death of Hamlet."), "type": "prose", "choices": None},

    {"character": "Claudius", "text": "He exits.", "type": "iambic", "choices": None}
]

fortinbras_dialogue = [
    {"character": "Fortinbras", 
     "text": "Go, Captain, from me greet the Danish king.", 
     "type": "iambic", 
     "choices": None},
    {"character": "Fortinbras", 
     "text": "Tell him that by his license Fortinbras", 
     "type": "iambic", 
     "choices": None},
    {"character": "Fortinbras", 
     "text": "Craves the conveyance of a promised march", 
     "type": "iambic", 
     "choices": None},
    {"character": "Fortinbras", 
     "text": "Over his kingdom. You know the rendezvous.", 
     "type": "iambic", 
     "choices": None},
    {"character": "Fortinbras", 
     "text": "If that his Majesty would aught with us,", 
     "type": "iambic", 
     "choices": None},
    {"character": "Fortinbras", 
     "text": "We shall express our duty in his eye;", 
     "type": "iambic", 
     "choices": None},
    {"character": "Fortinbras", 
     "text": "And let him know so.", 
     "type": "iambic", 
     "choices": None},

    {"character": "Captain", 
     "text": "I will do ’t, my lord.", 
     "type": "iambic", 
     "choices": None},

    {"character": "Fortinbras", 
     "text": "Go softly on.", 
     "type": "iambic", 
     "choices": None},

    {"character": "Hamlet", 
     "text": "Good sir, whose powers are these?", 
     "type": "iambic", 
     "choices": None},

    {"character": "Captain", 
     "text": "They are of Norway, sir.", 
     "type": "iambic", 
     "choices": None},

    {"character": "Hamlet", 
     "text": "How purposed, sir, I pray you?", 
     "type": "iambic", 
     "choices": None},

    {"character": "Captain", 
     "text": "Against some part of Poland.", 
     "type": "iambic", 
     "choices": None},

    {"character": "Hamlet", 
     "text": "Who commands them, sir?", 
     "type": "iambic", 
     "choices": None},

    {"character": "Captain", 
     "text": "The nephew to old Norway, Fortinbras.", 
     "type": "iambic", 
     "choices": None},

    {"character": "Hamlet", 
     "text": "Goes it against the main of Poland, sir,", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "Or for some frontier?", 
     "type": "iambic", 
     "choices": None},

    {"character": "Captain", 
     "text": "Truly to speak, and with no addition,", 
     "type": "iambic", 
     "choices": None},
    {"character": "Captain", 
     "text": "We go to gain a little patch of ground", 
     "type": "iambic", 
     "choices": None},
    {"character": "Captain", 
     "text": "That hath in it no profit but the name.", 
     "type": "iambic", 
     "choices": None},
    {"character": "Question", 
     "text": "How does Fortinbras' actions juxtapose with Hamlet's inaction?", 
     "type": "iambic", 
     "choices": [
        {"text": "Moral and Rationality", "correct": True},
        {"text": "Greed and Duplicity", "correct": False} ]},
    {"character": "Captain", 
     "text": "To pay five ducats, five, I would not farm it;", 
     "type": "iambic", 
     "choices": None},
    {"character": "Captain", 
     "text": "Nor will it yield to Norway or the Pole", 
     "type": "iambic", 
     "choices": None},
    {"character": "Captain", 
     "text": "A ranker rate, should it be sold in fee.", 
     "type": "iambic", 
     "choices": None},

    {"character": "Hamlet", 
     "text": "Why, then, the Polack never will defend it.", 
     "type": "iambic", 
     "choices": None},

    {"character": "Captain", 
     "text": "Yes, it is already garrisoned.", 
     "type": "iambic", 
     "choices": None},

    {"character": "Hamlet", 
     "text": "Two thousand souls and twenty thousand ducats", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "Will not debate the question of this straw.", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "This is th’ impostume of much wealth and peace,", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "That inward breaks and shows no cause without", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "Why the man dies.—I humbly thank you, sir.", 
     "type": "iambic", 
     "choices": None},

    {"character": "Captain", 
     "text": "God be wi’ you, sir.", 
     "type": "iambic", 
     "choices": None},

    {"character": "Rosencrantz", 
     "text": "Will ’t please you go, my lord?", 
     "type": "iambic", 
     "choices": None},

    {"character": "Hamlet", 
     "text": "I’ll be with you straight. Go a little before.", 
     "type": "iambic", 
     "choices": None},

    {"character": "Hamlet", 
     "text": "How all occasions do inform against me", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "And spur my dull revenge. What is a man", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "If his chief good and market of his time", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "Be but to sleep and feed? A beast, no more.", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "Sure He that made us with such large discourse,", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "Looking before and after, gave us not", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "That capability and godlike reason", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "To fust in us unused. Now whether it be", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "Bestial oblivion or some craven scruple", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "Of thinking too precisely on th’ event", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "A thought which, quartered, hath but one part wisdom", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "And ever three parts coward, I do not know", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "Why yet I live to say 'This thing’s to do,'", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "Sith I have cause, and will, and strength, and means", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "To do ’t. Examples gross as Earth exhort me:", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "Witness this army of such mass and charge,", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "Led by a delicate and tender prince,", 
     "type": "iambic", 
     "choices": None},

     {"character": "Question", 
     "text": "What theme is set up from the above quote?", 
     "choices": [
        {"text": "Gender Roles", "correct": True},
        {"text": "Religion", "correct": False} ]},

    {"character": "Hamlet", 
     "text": "Whose spirit with divine ambition puffed", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "Makes mouths at the invisible event,", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "Exposing what is mortal and unsure", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "To all that fortune, death, and danger dare,", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "Even for an eggshell. Rightly to be great", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "Is not to stir without great argument,", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "But greatly to find quarrel in a straw", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "When honor’s at the stake. How stand I, then,", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "That have a father killed, a mother stained,", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "Excitements of my reason and my blood,", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "And let all sleep, while to my shame I see", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "The imminent death of twenty thousand men,", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "That for a fantasy and trick of fame", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "Go to their graves like beds, fight for a plot", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "Whereon the numbers cannot try the cause,", 
     "type": "iambic",
     "choices": None},
    {"character": "Hamlet", 
     "text": "Which is not tomb enough and continent", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "To hide the slain? O, from this time forth", 
     "type": "iambic", 
     "choices": None},
    {"character": "Hamlet", 
     "text": "My thoughts be bloody or be nothing worth!", 
     "type": "iambic", 
     "choices": None},

    {"character": "Question", 
     "text": "What Quote can be connected with the line above?", 
     "choices": [
        {"text": "Act 3 Scene 2, Lines 427-428", "correct": True},
        {"text": "Act 1 Scene 5, Lines 151-160", "correct": False} ]}
]